// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOg82onwdBhyGyKAcrlLUa4xIOW6fXS2A',
    appId: '1:925938950295:web:345f4ce460e2d6443e49d2',
    messagingSenderId: '925938950295',
    projectId: 'budgetlite-4d8e9',
    authDomain: 'budgetlite-4d8e9.firebaseapp.com',
    storageBucket: 'budgetlite-4d8e9.firebasestorage.app',
    measurementId: 'G-46X2Q27S1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG73rhkMncErtAtABKwXX4Y__XOzkSLRI',
    appId: '1:925938950295:android:303491db79a2218d3e49d2',
    messagingSenderId: '925938950295',
    projectId: 'budgetlite-4d8e9',
    storageBucket: 'budgetlite-4d8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMPWlSuWeIqyotT21NrV3CbCPEp2GW14M',
    appId: '1:925938950295:ios:2f252343354bb3ff3e49d2',
    messagingSenderId: '925938950295',
    projectId: 'budgetlite-4d8e9',
    storageBucket: 'budgetlite-4d8e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMPWlSuWeIqyotT21NrV3CbCPEp2GW14M',
    appId: '1:925938950295:ios:2f252343354bb3ff3e49d2',
    messagingSenderId: '925938950295',
    projectId: 'budgetlite-4d8e9',
    storageBucket: 'budgetlite-4d8e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOg82onwdBhyGyKAcrlLUa4xIOW6fXS2A',
    appId: '1:925938950295:web:2f2940eca0a46e643e49d2',
    messagingSenderId: '925938950295',
    projectId: 'budgetlite-4d8e9',
    authDomain: 'budgetlite-4d8e9.firebaseapp.com',
    storageBucket: 'budgetlite-4d8e9.firebasestorage.app',
    measurementId: 'G-4XKKCQVD9L',
  );
}
